#!/usr/bin/env python3
"""Rebuild library/index.jsonl and library/INDEX.md from the set files.

The index is derived data — safe to delete and regenerate at any time.
``index.jsonl`` is one question per line (handy for grep/jq and fast dedup);
``INDEX.md`` is a human-readable roll-up with per-set listings and global stats.

Usage:
    python scripts/build_index.py
"""

import json
import os
import sys

import trivialib as T


def main():
    root = T.repo_root()
    lib_dir = os.path.join(root, "library")
    questions = T.load_library(root)

    # index.jsonl
    jsonl_path = os.path.join(lib_dir, "index.jsonl")
    with open(jsonl_path, "w", encoding="utf-8") as fh:
        for q in questions:
            row = {
                "set_id": q.get("set_id"),
                "topic": q.get("topic", ""),
                "id": q.get("id"),
                "dimension": q.get("dimension"),
                "answer_subject": q.get("answer_subject") or q.get("state"),
                "q": q.get("q"),
            }
            fh.write(json.dumps(row, ensure_ascii=False) + "\n")

    # INDEX.md
    dims = {}
    subjects = set()
    topics = {}
    sets_seen = {}
    for q in questions:
        d = (q.get("dimension") or "").strip().lower()
        dims[d] = dims.get(d, 0) + 1
        subjects.add(T.subject_fingerprint(q))
        t = q.get("topic", "")
        topics[t] = topics.get(t, 0) + 1
        sets_seen.setdefault(q.get("set_id"), []).append(q)

    lines = []
    lines.append("# Question library index")
    lines.append("")
    lines.append("_Generated by `scripts/build_index.py` — do not edit by hand._")
    lines.append("")
    lines.append("- **Sets:** %d" % len(sets_seen))
    lines.append("- **Questions:** %d" % len(questions))
    lines.append("- **Distinct answer subjects:** %d" % len(subjects))
    lines.append("- **Distinct dimensions:** %d" % len([d for d in dims if d]))
    lines.append("")
    lines.append("## Dimensions used (most to least)")
    lines.append("")
    for d, c in sorted(dims.items(), key=lambda kv: (-kv[1], kv[0])):
        lines.append("- `%s` \u00d7 %d" % (d or "(unset)", c))
    lines.append("")
    lines.append("## Sets")
    lines.append("")
    for set_id in sorted(sets_seen):
        qs = sets_seen[set_id]
        topic = qs[0].get("topic", "")
        lines.append("### %s  (%s, %d questions)" % (set_id, topic, len(qs)))
        for q in qs:
            lines.append("- **%s** \u2014 %s _(%s)_" % (
                q.get("answer_subject") or q.get("state"),
                q.get("q", ""),
                q.get("dimension", ""),
            ))
        lines.append("")

    with open(os.path.join(lib_dir, "INDEX.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    print("Wrote %s (%d questions) and INDEX.md" % (jsonl_path, len(questions)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
